config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :items do
    resources :item_comments, only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
end

app/models/item.rb
class Item < ApplicationRecord
	mount_uploader :img, ImgUploader
	belongs_to :user
	has_many :item_comments, dependent: :destroy
	validates :name, presence: true
	validates :contents, presence: true, length: {maximum: 200}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :correct_user,   only: [:edit, :update]

	def new
		@item = Item.new
    end

    def create
    	@item = Item.new(item_params)
    	@item.user_id = current_user.id
    	if @item.save
        flash[:sucess] = 'レビューを投稿をしました'
    	redirect_to items_url
        else
            @items = Item.all
            render :new
        end
    end

    def index
    	@item = Item.new
    	@items = Item.all
    end

    def show
        @item = Item.find(params[:id])
        @item_comment = ItemComment.new
    end

    def edit
        @item = Item.find(params[:id])
    end

    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
        flash[:sucess] = 'レビューを更新しました'
        redirect_to item_url(@item.id)
        else
            render :edit
        end
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to items_url
    end

    def correct_user
      @item = Item.find(params[:id])
      @user = @item.user
      if current_user != @user
      redirect_to items_path
      end
    end

    private
    	def item_params
    		params.require(:item).permit(:name, :price, :maker, :link, :contents, :img, :user_id)
    	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Editing Item</h1>
<%= form_for(@item) do |f| %>

    <ul class="form_name">
    <li><%= f.label :name, "Name" %></li>
    <li><%= f.text_field :name %></li>
  </ul>
    <ul class="form_price">
    <li><%= f.label :price, "Price" %></li>
    <li><%= f.text_area :price %></li>
  </ul>
    <ul class="form_maker">
    <li><%= f.label :maker, "Maker" %></li>
    <li><%= f.text_area :maker %></li>
  </ul>
    <ul class="form_link">
    <li><%= f.label :link, "Link" %></li>
    <li><%= f.text_area :link %></li>
  </ul>
    <ul class="form_contents">
    <li><%= f.label :contents, "Contents" %></li>
    <li><%= f.text_area :contents %></li>
  </ul>
  <ul class="form_img">
    <li><%= f.label :img, "Image" %></li>
    <li><%= f.file_field :img %></li>
  </ul>

    <div class="btn"><%= f.submit 'Update item' %></div>
<% end %>

<%= link_to "Show", item_path(@item.id) %>
<%= "|" %>
<%= link_to "Back", items_path %>

app/views/items/index.html.erb
<h2>Items</h2>

<% @items.each do |item| %>
<ul class="item">
<li><%= item.name %></li>
<li><%= item.price %></li>
<li><%= item.maker %></li>
<li><%= item.link %></li>
<li><%= item.contents %></li>
<% if item.img? %>
<%= link_to (image_tag item.img.url), item_path(item.id) %>
<% else %>
<%= link_to (image_tag "/assets/no_image.jpg"), item_path(item.id) %>
<% end %>

</ul>
<% end %>

app/views/items/new.html.erb
<%= form_for(@item) do |f| %>

  <% if @item.errors.any? %>
  <h3><%= @item.errors.count %>errors prohibited this book from being saved:</h3>
  <% @item.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>
<% end %>

<% end %>

<h2>New Item</h2>

    <ul class="form_name">
    <li><%= f.label :name, "Name" %></li>
    <li><%= f.text_field :name %></li>
	</ul>
    <ul class="form_price">
    <li><%= f.label :price, "Price" %></li>
    <li><%= f.text_area :price %></li>
	</ul>
    <ul class="form_maker">
    <li><%= f.label :maker, "Maker" %></li>
    <li><%= f.text_area :maker %></li>
	</ul>
    <ul class="form_link">
    <li><%= f.label :link, "Link" %></li>
    <li><%= f.text_area :link %></li>
	</ul>
    <ul class="form_contents">
    <li><%= f.label :contents, "Contents" %></li>
    <li><%= f.text_area :contents %></li>
	</ul>
	<ul class="form_img">
    <li><%= f.label :img, "Image" %></li>
    <li><%= f.file_field :img %></li>
	</ul>

    <div class="btn"><%= f.submit "Create Item" %></div>

<% end %>

app/views/items/show.html.erb
<p><strong>Name: </strong><%= @item.name %></p>

<p><strong>Price: </strong><%= @item.price %></p>

<p><strong>Maker: </strong><%= @item.maker %></p>

<p><strong>Link: </strong><%= @item.link %></p>

<p><strong>Contents: </strong><%= @item.contents %></p>

<% if @item.img? %>
<p><%= image_tag @item.img.url %></p>
<% else %>
<p><%= image_tag "/assets/no_image.jpg" %></p>
<% end %>

<%= link_to "Back", items_path %>
<% if @item.user == current_user %>
<%= "|" %>
<%= link_to "Edit", edit_item_path %>
<%= "|" %>
<%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


<% @item.item_comments.each do |item_comment| %>
	<div>
		<%= item_comment.user.name %>
		<%= item_comment.created_at.strftime('%Y/%m/%d') %>
		<%= item_comment.comment %>
		<% if @item_comment.user == current_user %>
		<%= link_to "Delete", item_item_comment_path(@item, item_comment[:id]), method: :delete, data: { confirm: "Are You sure?" } %>
		<% end %>
	</div>
<% end %>

<%= form_for [@item, @item_comment] do |f| %>
<%= f.text_area :comment %>
<%= f.submit 'Create Comment' %>
<% end %>